CREATE DATABASE IF NOT EXISTS tools_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tools_db;

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO admins (username, password) VALUES
('admin', 'admin123');

CREATE TABLE IF NOT EXISTS tools (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cat VARCHAR(50) NOT NULL,
    badge VARCHAR(20) NOT NULL,
    description TEXT NOT NULL,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO tools (name, cat, badge, description, url) VALUES
('ChatGPT', 'ai', 'free', 'AI assistant from OpenAI that helps with almost anything', 'https://chat.openai.com'),
('Claude', 'ai', 'free', 'Smart assistant from Anthropic, great for writing and analysis', 'https://claude.ai'),
('Gemini', 'ai', 'free', 'Google''s AI assistant integrated with all their services', 'https://gemini.google.com'),
('Perplexity', 'ai', 'free', 'AI-powered search engine with cited sources', 'https://perplexity.ai'),
('Midjourney', 'ai', 'paid', 'Generates high-quality images from text prompts', 'https://midjourney.com'),
('ElevenLabs', 'ai', 'free', 'Converts text into realistic human-like voice', 'https://elevenlabs.io'),
('Runway', 'ai', 'free', 'AI-powered video generation and editing', 'https://runwayml.com'),
('Grok', 'ai', 'free', 'AI assistant from xAI by Elon Musk', 'https://grok.x.ai'),
('Copilot', 'ai', 'free', 'Microsoft''s AI assistant built into Windows', 'https://copilot.microsoft.com'),
('Adobe Firefly', 'ai', 'free', 'Adobe''s AI image generation tool', 'https://firefly.adobe.com'),
('Sora', 'ai', 'paid', 'Generates realistic videos from text descriptions only', 'https://openai.com/sora'),
('Figma', 'design', 'free', 'The most popular UI design tool on the internet', 'https://figma.com'),
('Canva', 'design', 'free', 'Design posts and presentations easily with no experience', 'https://canva.com'),
('Coolors', 'design', 'free', 'Generates harmonious color palettes for your project', 'https://coolors.co'),
('Unsplash', 'design', 'free', 'Free high-quality stock photos', 'https://unsplash.com'),
('Iconify', 'design', 'free', 'Thousands of free icons', 'https://iconify.design'),
('Framer', 'design', 'free', 'Build beautiful websites with almost no code', 'https://framer.com'),
('Remove.bg', 'design', 'free', 'Removes image backgrounds in one second', 'https://remove.bg'),
('Pexels', 'design', 'free', 'Free high-quality photos and videos', 'https://pexels.com'),
('Google Fonts', 'design', 'free', 'Thousands of free fonts from Google', 'https://fonts.google.com'),
('Spline', 'design', 'free', 'Design 3D elements for the web', 'https://spline.design'),
('Looka', 'design', 'paid', 'Design your company logo using AI', 'https://looka.com'),
('CapCut', 'video', 'free', 'Easy and popular video editing app', 'https://capcut.com'),
('DaVinci Resolve', 'video', 'free', 'Professional and free video editing software', 'https://blackmagicdesign.com/products/davinciresolve'),
('Descript', 'video', 'free', 'Edit video by editing its transcript', 'https://descript.com'),
('OBS Studio', 'video', 'free', 'Screen recording and live streaming for free', 'https://obsproject.com'),
('Handbrake', 'video', 'free', 'Compress and convert video to any format for free', 'https://handbrake.fr'),
('Grammarly', 'writing', 'free', 'Corrects English writing mistakes', 'https://grammarly.com'),
('Quillbot', 'writing', 'free', 'Rewrites text in different ways', 'https://quillbot.com'),
('Copy.ai', 'writing', 'free', 'Write marketing content using AI', 'https://copy.ai'),
('Hemingway', 'writing', 'free', 'Simplifies your writing and makes it clearer', 'https://hemingwayapp.com'),
('Wordtune', 'writing', 'free', 'Suggests different ways to write the same sentence', 'https://wordtune.com'),
('Hugging Face', 'ai', 'free', 'The largest open-source AI models platform', 'https://huggingface.co'),
('Stable Diffusion', 'ai', 'free', 'Free open-source image generation you install locally', 'https://stability.ai'),
('Kling AI', 'ai', 'free', 'Professional video generation from text and images', 'https://klingai.com'),
('Ideogram', 'ai', 'free', 'Generates images with clear embedded text at high accuracy', 'https://ideogram.ai'),
('Leonardo AI', 'ai', 'free', 'Multi-style image generation for games and design', 'https://leonardo.ai'),
('Gamma', 'ai', 'free', 'Turns your ideas into professional presentations automatically', 'https://gamma.app'),
('Otter.ai', 'ai', 'free', 'Converts conversations and meetings into written text', 'https://otter.ai'),
('Elicit', 'ai', 'free', 'Scientific research assistant that summarizes papers', 'https://elicit.com'),
('Consensus', 'ai', 'free', 'Searches scientific studies and answers with reliable evidence', 'https://consensus.app'),
('You.com', 'ai', 'free', 'AI-powered search engine with high privacy', 'https://you.com'),
('Phind', 'ai', 'free', 'AI-powered search engine for programmers', 'https://phind.com'),
('Cursor', 'ai', 'free', 'AI code editor that writes code with you', 'https://cursor.sh'),
('v0', 'ai', 'free', 'Generates web interfaces from text descriptions quickly', 'https://v0.dev'),
('Bolt.new', 'ai', 'free', 'Builds complete apps from a simple text idea', 'https://bolt.new'),
('Lovable', 'ai', 'free', 'Converts text descriptions into real web apps', 'https://lovable.dev'),
('Windsurf', 'ai', 'free', 'Smart code editor from Codeium with powerful AI features', 'https://codeium.com/windsurf'),
('Napkin', 'ai', 'free', 'Converts text into illustrations and diagrams automatically', 'https://napkin.ai'),
('Suno', 'ai', 'free', 'Generates complete songs from text using AI', 'https://suno.com'),
('Udio', 'ai', 'free', 'Generate professional music using AI', 'https://udio.com'),
('Hailuo', 'ai', 'free', 'Generate realistic video from images and text', 'https://hailuoai.com'),
('Adobe Express', 'design', 'free', 'Quick design tool from Adobe with ready templates', 'https://express.adobe.com'),
('Vectr', 'design', 'free', 'Free vector design tool that works in the browser', 'https://vectr.com'),
('Photopea', 'design', 'free', 'Full free Photoshop that works in the browser', 'https://photopea.com'),
('GIMP', 'design', 'free', 'Free and open-source image editing software', 'https://gimp.org'),
('Inkscape', 'design', 'free', 'Free and open-source vector design software', 'https://inkscape.org'),
('Pixlr', 'design', 'free', 'Edit photos online with professional tools', 'https://pixlr.com'),
('Placeit', 'design', 'free', 'Mockups and templates to showcase your designs', 'https://placeit.net'),
('Storyset', 'design', 'free', 'Free customizable illustrations', 'https://storyset.com'),
('unDraw', 'design', 'free', 'Free SVG illustrations for any project', 'https://undraw.co'),
('Haikei', 'design', 'free', 'Generate unique SVG backgrounds and shapes for websites', 'https://haikei.app'),
('Rive', 'design', 'free', 'Create interactive animations for websites and apps', 'https://rive.app'),
('Lottie Files', 'design', 'free', 'Huge library of free animations for developers', 'https://lottiefiles.com'),
('Colorhunt', 'design', 'free', 'Color palettes curated by real designers', 'https://colorhunt.co'),
('Shots.so', 'design', 'free', 'Professional mockups to showcase your apps and sites', 'https://shots.so'),
('Screely', 'design', 'free', 'Turns your screenshot into a beautiful professional image', 'https://screely.com'),
('Kdenlive', 'video', 'free', 'Powerful open-source video editing software.', 'https://kdenlive.org'),
('Shotcut', 'video', 'free', 'Simple free video editor for all platforms.', 'https://shotcut.org'),
('Clipchamp', 'video', 'free', 'Microsoft video editor built into Windows.', 'https://clipchamp.com'),
('Veed.io', 'video', 'free', 'Online video editor with automatic captions.', 'https://veed.io'),
('Invideo AI', 'video', 'free', 'Turn text into professional videos with AI.', 'https://invideo.io'),
('Pictory', 'video', 'free', 'Automatically turn articles and text into videos.', 'https://pictory.ai'),
('HeyGen', 'video', 'free', 'Create videos with realistic human avatars.', 'https://heygen.com'),
('Synthesia', 'video', 'paid', 'Training videos with human avatars.', 'https://synthesia.io'),
('Loom ScreenStudio', 'video', 'free', 'Professional screen recording with polished effects.', 'https://screenstudio.lemonsqueezy.com'),
('Notion AI', 'writing', 'paid', 'Smart writing assistant built into Notion', 'https://notion.so/product/ai'),
('Jasper', 'writing', 'paid', 'Write professional marketing content with AI', 'https://jasper.ai'),
('Writesonic', 'writing', 'free', 'Write articles and ads with AI', 'https://writesonic.com'),
('Rytr', 'writing', 'free', 'AI writing assistant at affordable prices', 'https://rytr.me'),
('Sudowrite', 'writing', 'paid', 'AI assistant for creative and novel writing', 'https://sudowrite.com'),
('ProWritingAid', 'writing', 'free', 'Deep grammar and style check for writers', 'https://prowritingaid.com'),
('LanguageTool', 'writing', 'free', 'Spelling and grammar check supporting Arabic', 'https://languagetool.org'),
('DeepL', 'writing', 'free', 'Very accurate translation surpassing Google Translate', 'https://deepl.com'),
('Speechify', 'writing', 'free', 'Reads any text or article to you in a natural voice', 'https://speechify.com'),
('Readwise', 'writing', 'paid', 'Saves your book quotes and reminds you daily', 'https://readwise.io'),
('Mistral AI', 'ai', 'free', 'Fast, open European AI models', 'https://mistral.ai'),
('Meta AI', 'ai', 'free', 'Meta''s AI assistant built into WhatsApp and Instagram', 'https://meta.ai'),
('Poe', 'ai', 'free', 'A platform that brings multiple AI models together in one place', 'https://poe.com'),
('Character.AI', 'ai', 'free', 'Chat with a variety of AI characters', 'https://character.ai'),
('Janitor AI', 'ai', 'free', 'Conversations with custom AI characters', 'https://janitor.ai'),
('Perplexity Labs', 'ai', 'free', 'Try Perplexity''s latest AI models', 'https://labs.perplexity.ai'),
('Groq', 'ai', 'free', 'Run AI models at lightning speed for free', 'https://groq.com'),
('Together AI', 'ai', 'free', 'Run open-source models in the cloud', 'https://together.ai'),
('Replicate', 'ai', 'free', 'Run a variety of AI models through an API', 'https://replicate.com'),
('Fal.ai', 'ai', 'free', 'Generate images and videos with multiple models quickly', 'https://fal.ai'),
('Playground AI', 'ai', 'free', 'Generate professional images for free with multiple models', 'https://playground.com'),
('Krea AI', 'ai', 'free', 'Generate and enhance images with AI in real time', 'https://krea.ai'),
('Magnific AI', 'ai', 'paid', 'Upscale images and improve their quality with AI', 'https://magnific.ai'),
('Topaz Photo AI', 'ai', 'paid', 'Professionally enhance image quality and remove noise', 'https://topazlabs.com'),
('Luma AI', 'ai', 'free', 'Generate 3D video from images and text', 'https://lumalabs.ai'),
('Hedra', 'ai', 'free', 'Animate images and make them talk with AI', 'https://hedra.com'),
('D-ID', 'ai', 'free', 'Animate face photos and create talking videos', 'https://d-id.com'),
('Rask AI', 'ai', 'free', 'Translate and dub videos with AI', 'https://rask.ai'),
('Captions AI', 'ai', 'free', 'Add automatic subtitles to videos with high accuracy', 'https://captions.ai'),
('Whisper', 'ai', 'free', 'Convert speech to text with high accuracy from OpenAI', 'https://openai.com/research/whisper'),
('AssemblyAI', 'ai', 'free', 'A powerful API for speech-to-text with advanced analysis', 'https://assemblyai.com'),
('Deepgram', 'ai', 'free', 'Convert speech to text at high speed via API', 'https://deepgram.com'),
('NotebookLM', 'ai', 'free', 'Google''s research assistant that analyzes your files and documents', 'https://notebooklm.google.com'),
('Gemini Advanced', 'ai', 'paid', 'Google''s most powerful model with advanced capabilities', 'https://gemini.google.com/advanced'),
('Claude Projects', 'ai', 'free', 'Create organized projects with long-term memory in Claude', 'https://claude.ai'),
('Aria', 'ai', 'free', 'Opera''s AI assistant built into the browser', 'https://opera.com/features/aria'),
('Copilot Studio', 'ai', 'paid', 'Build custom chatbots with AI', 'https://copilotstudio.microsoft.com'),
('Dify', 'ai', 'free', 'An open platform for building AI applications', 'https://dify.ai'),
('Flowise', 'ai', 'free', 'Build AI workflows with a visual interface', 'https://flowiseai.com'),
('LangChain', 'ai', 'free', 'A framework for building LLM apps for developers', 'https://langchain.com'),
('Whisk', 'design', 'free', 'Google''s tool for generating images by blending images together', 'https://labs.google/fx/tools/whisk'),
('Adobe Illustrator', 'design', 'paid', 'The world''s most famous vector design software', 'https://adobe.com/products/illustrator'),
('Adobe Photoshop', 'design', 'paid', 'The professional image-editing standard for decades', 'https://adobe.com/products/photoshop'),
('Affinity Designer', 'design', 'paid', 'A professional Illustrator alternative at a much lower price', 'https://affinity.serif.com/designer'),
('Sketch', 'design', 'paid', 'A popular UI design tool for Mac users', 'https://sketch.com'),
('Lunacy', 'design', 'free', 'A free Figma alternative that works offline', 'https://icons8.com/lunacy'),
('Penpot', 'design', 'free', 'An open-source, self-hostable UI design tool', 'https://penpot.app'),
('Maze', 'design', 'free', 'User testing and feedback collection for designs', 'https://maze.co'),
('Hotjar', 'design', 'free', 'Track user behavior on your site with heatmaps', 'https://hotjar.com'),
('Zeplin', 'design', 'free', 'Deliver designs to developers with precise specs', 'https://zeplin.io'),
('Abstract', 'design', 'paid', 'Manage design file versions like Git', 'https://abstract.com'),
('Noun Project', 'design', 'free', 'Millions of icons and symbols for design', 'https://thenounproject.com'),
('Flaticon', 'design', 'free', 'The largest free icon library online', 'https://flaticon.com'),
('SVGRepo', 'design', 'free', 'A huge library of free SVG files', 'https://svgrepo.com'),
('Duotone', 'design', 'free', 'Apply a two-color effect to images easily', 'https://duotone.shapefactory.co'),
('Photor', 'design', 'free', 'Edit and filter images online quickly', 'https://photor.io'),
('Cleanup.pictures', 'design', 'free', 'Remove any element from an image with AI', 'https://cleanup.pictures'),
('Upscayl', 'design', 'free', 'Upscale images with AI for free and offline', 'https://upscayl.org'),
('Squoosh', 'design', 'free', 'Compress images with high quality directly in the browser', 'https://squoosh.app'),
('SVGOMG', 'design', 'free', 'Optimize and shrink SVG files quickly', 'https://jakearchibald.github.io/svgomg'),
('Pattern.monster', 'design', 'free', 'Generate custom SVG backgrounds and patterns for projects', 'https://pattern.monster'),
('Fffuel', 'design', 'free', 'A set of tools for generating SVG backgrounds and shapes', 'https://fffuel.co'),
('Bgjar', 'design', 'free', 'Generate beautiful SVG backgrounds in one click', 'https://bgjar.com'),
('Mesh Gradient', 'design', 'free', 'Generate beautiful gradient backgrounds for projects', 'https://meshgradient.in'),
('Brandmark', 'design', 'paid', 'Generate a complete brand identity with AI', 'https://brandmark.io'),
('Namelix', 'design', 'free', 'Generate smart brand names and initial logos', 'https://namelix.com'),
('Mockuphone', 'design', 'free', 'Mock up mobile apps with realistic phone frames', 'https://mockuphone.com'),
('Smartmockups', 'design', 'free', 'Professional mockups for all devices and products', 'https://smartmockups.com'),
('iMovie', 'video', 'free', 'Easy and free video editing for Apple users', 'https://apple.com/imovie'),
('Final Cut Pro', 'video', 'paid', 'Professional video editing for Mac users', 'https://apple.com/final-cut-pro'),
('Adobe Premiere Pro', 'video', 'paid', 'The industry standard for professional video editing', 'https://adobe.com/products/premiere'),
('Adobe After Effects', 'video', 'paid', 'Create professional visual effects and motion graphics', 'https://adobe.com/products/aftereffects'),
('Motion', 'video', 'paid', 'Motion graphics software from Apple for Mac users', 'https://apple.com/motion'),
('Blender', 'video', 'free', 'Full free 3D and motion graphics software', 'https://blender.org'),
('Rive Animate', 'video', 'free', 'Create interactive animations for web and apps', 'https://rive.app'),
('Animaker', 'video', 'free', 'Create animated videos without experience', 'https://animaker.com'),
('Vyond', 'video', 'paid', 'Create professional animated videos for business', 'https://vyond.com'),
('Powtoon', 'video', 'free', 'Animated presentation videos made easy', 'https://powtoon.com'),
('Biteable', 'video', 'free', 'Create short marketing videos quickly', 'https://biteable.com'),
('Vidyard', 'video', 'free', 'Record and send videos to clients and colleagues', 'https://vidyard.com'),
('Streamyard', 'video', 'free', 'Professional live streaming on multiple platforms at once', 'https://streamyard.com'),
('Riverside.fm', 'video', 'free', 'Record podcast and video in studio quality over the internet', 'https://riverside.fm'),
('Squadcast', 'video', 'free', 'Record podcasts and interviews in high quality', 'https://squadcast.fm'),
('Cleanvoice', 'video', 'free', 'Remove filler words and noise from your recordings', 'https://cleanvoice.ai'),
('Auphonic', 'video', 'free', 'Automatically improve audio quality for podcasts', 'https://auphonic.com'),
('Podbean', 'video', 'free', 'Publish and host your podcast on all platforms', 'https://podbean.com'),
('Buzzsprout', 'video', 'free', 'Host and publish podcasts easily', 'https://buzzsprout.com'),
('Castbox', 'video', 'free', 'Podcast listening app with massive content', 'https://castbox.fm'),
('Substack', 'writing', 'free', 'Publish a newsletter and get subscribers and income', 'https://substack.com'),
('Medium', 'writing', 'free', 'Publish articles and reach millions of readers', 'https://medium.com'),
('Ghost', 'writing', 'free', 'Open-source publishing platform for writers and journalists', 'https://ghost.org'),
('Beehiiv', 'writing', 'free', 'Professional newsletter with powerful growth tools', 'https://beehiiv.com'),
('ConvertKit', 'writing', 'free', 'Build an email list and send newsletters for creators', 'https://convertkit.com'),
('Mailchimp', 'writing', 'free', 'Send newsletters and marketing campaigns', 'https://mailchimp.com'),
('Canary Mail', 'writing', 'free', 'Smart mail app with AI summaries', 'https://canarymail.io'),
('Ulysses', 'writing', 'paid', 'Professional writing editor for Apple users', 'https://ulysses.app'),
('iA Writer', 'writing', 'paid', 'Write without distractions with a very clean interface', 'https://ia.net/writer'),
('Scrivener', 'writing', 'paid', 'Software for writing novels and long-form projects', 'https://literatureandlatte.com/scrivener'),
('Reedsy', 'writing', 'free', 'Book writing and publishing tools with editor network', 'https://reedsy.com'),
('Atticus', 'writing', 'paid', 'Format and design books for self-publishing', 'https://atticus.io'),
('Vellum', 'writing', 'paid', 'Design professional books for Amazon and other stores', 'https://vellum.pub'),
('Manuskript', 'writing', 'free', 'Open-source novel and story writing', 'https://theologeek.ch/manuskript'),
('Bibisco', 'writing', 'free', 'Structured novel writing with character development', 'https://bibisco.com'),
('Khan Academy', 'education', 'free', 'Free lessons in math, science and more for all levels', 'https://khanacademy.org'),
('Coursera', 'education', 'free', 'Courses from top universities with accredited certificates', 'https://coursera.org'),
('edX', 'education', 'free', 'Learn from MIT, Harvard and other world universities for free', 'https://edx.org'),
('Udemy', 'education', 'paid', 'Thousands of courses in all fields at reasonable prices', 'https://udemy.com'),
('Skillshare', 'education', 'free', 'Creative courses in design, art and writing', 'https://skillshare.com'),
('LinkedIn Learning', 'education', 'paid', 'Professional courses from LinkedIn with resume certificates', 'https://linkedin.com/learning'),
('Brilliant', 'education', 'free', 'Learn math and science interactively and enjoyably', 'https://brilliant.org'),
('Wolfram Alpha', 'education', 'free', 'Solve math and science problems with detailed steps', 'https://wolframalpha.com'),
('Quizlet', 'education', 'free', 'Flashcards and quizzes to memorize any subject', 'https://quizlet.com'),
('Photomath', 'education', 'free', 'Solve math problems with camera and step-by-step explanation', 'https://photomath.com'),
('Socratic', 'education', 'free', 'Homework help with AI from Google', 'https://socratic.org'),
('Chegg', 'education', 'paid', 'Textbook solutions and homework help', 'https://chegg.com'),
('Grammarly EDU', 'education', 'free', 'Improve academic writing for students and researchers', 'https://grammarly.com/edu'),
('Canva for Education', 'education', 'free', 'Design presentations and educational materials free for students', 'https://canva.com/education'),
('Google Scholar', 'education', 'free', 'Search engine specialized in scientific papers and research', 'https://scholar.google.com'),
('ResearchGate', 'education', 'free', 'Network for researchers and sharing scientific papers', 'https://researchgate.net'),
('Sci-Hub', 'education', 'free', 'Access paid scientific research for free', 'https://sci-hub.se'),
('MIT OpenCourseWare', 'education', 'free', 'Complete free study materials from MIT', 'https://ocw.mit.edu'),
('TED-Ed', 'education', 'free', 'Short and useful lessons in the engaging TED style', 'https://ed.ted.com'),
('Crash Course', 'education', 'free', 'Quick and concise explanation of all subjects', 'https://thecrashcourse.com'),
('Codecademy', 'education', 'free', 'Learn programming interactively for beginners', 'https://codecademy.com'),
('freeCodeCamp', 'education', 'free', 'Learn web development free with real projects', 'https://freecodecamp.org'),
('The Odin Project', 'education', 'free', 'Comprehensive curriculum for learning web development from scratch', 'https://theodinproject.com'),
('CS50', 'education', 'free', 'The world''s most famous programming course from Harvard', 'https://cs50.harvard.edu');
